### ISSUE TITLE
Permission to include in clink-completions?

### ISSUE THREAD

**Issue by chrisant996** [dodmi/Clink-Addons#1]
@dodmi I just found this today.  I don't see a license file here, so I would assume there are no licensing restrictions, but I want to double check.

May I make modified versions of these completion scripts and include them in the clink-completions repo?

**Comment by dodmi** [comment]
Hi @chrisant996,

I made them for myself and thought they might also be useful for others. 
Feel free to add them to your repo and improve them as you like.

Kind regards

**Comment by chrisant996** [comment]
@dodmi Thank you! I will indeed copy+modify and add them to [clink-completions](https://github.com/vladimir-kotikov/clink-completions).
